export default {
  'APP': {
    'LAST_UPDATE': 'APP_LAST_UPDATE',
    'REGIONS': 'APP_REGIONS',
    'CURRENT_VIEW': 'APP_CURRENT_VIEW',
    'CURRENT_AGGREGATE': 'APP_CURRENT_AGGREGATE',
    'CHANGE_FILTERS': 'APP_CHANGE_FILTER'
  },
  'DATA': {
    'READ_BY_DATE': 'READ_DATA_BY_DATE',
    'READ_BY_AGGREGATE': 'READ_DATA_BY_AGGREGATE',
    'READ_REGION_AGGREGATE': 'READ_REGION_AGGREGATE',
    'CLEAR': 'DATA_CLEAR'
  }
}